        <script type="text/javascript" src="javascripts/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="javascripts/shoppinglist.js"></script>
        <script type="text/javascript" src="javascripts/shoppinglist.helper.js"></script>
        <script type="text/javascript" src="javascripts/shoppinglist.page.js"></script>
        <script type="text/javascript" src="javascripts/shoppinglist.mod.login.js"></script>
        <script type="text/javascript" src="javascripts/shoppinglist.mod.register.js"></script>
        <script type="text/javascript" src="javascripts/shoppinglist.mod.households.js"></script>
        <script type="text/javascript" src="javascripts/shoppinglist.mod.shoppinglists.js"></script>
        <script type="text/javascript" src="javascripts/shoppinglist.mod.items.js"></script>
        <script type="text/javascript" src="javascripts/shoppinglist.mod.invite.js"></script>                